Fixes

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,2 +1,50 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# bin/compile BUILD_DIR CACHE_DIR ENV_DIR
+
+# fail fast
+set -e
+
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
+
+export_env_dir() {
+  env_dir=$1
+  whitelist_regex=${2:-''}
+  blacklist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH)$'}
+  if [ -d "$env_dir" ]; then
+    for e in $(ls $env_dir); do
+      echo "$e" | grep -E "$whitelist_regex" | grep -qvE "$blacklist_regex" &&
+      export "$e=$(cat $env_dir/$e)"
+      :
+    done
+  fi
+}
+
+export_env_dir ENV_DIR
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+function set_env_var() {
+  ENV_VAR_NAME=$1
+  ENV_VAR_VALUE=$2
+  echo -n "$ENV_VAR_VALUE" > $ENV_DIR/$ENV_VAR_NAME
+  echo "$ENV_VAR_NAME = $ENV_VAR_VALUE" | indent
+}
+
+echo "-----> Running compile..."
+
+set_env_var "PATH" "$BUILD_DIR/.apt/usr/bin:$PATH"
+set_env_var "LD_LIBRARY_PATH" "$BUILD_DIR/.apt/usr/lib:$LD_LIBRARY_PATH"
+set_env_var "LIBRARY_PATH" "$BUILD_DIR/.apt/usr/lib:$LIBRARY_PATH"
+set_env_var "INCLUDE_PATH" "$BUILD_DIR/.apt/usr/include:$INCLUDE_PATH"
+set_env_var "CPATH" "$INCLUDE_PATH"
+set_env_var "CPPPATH" "$INCLUDE_PATH"
+
 set_env_var "BUNDLE_BUILD__CHARLOCK_HOLMES" "--with-icu-dir=\"$BUILD_DIR/.apt/usr\""
